// This file is autogenerated by scripts/generate-projects.js
// Run: node scripts/generate-projects.js

import { Project } from '@/types/project';

export const projects: Project[] = [
  {
    "title": "KFC",
    "tags": [
      "KFC"
    ],
    "categories": [
      "commercial"
    ],
    "date": "2025-11-06",
    "media": [
      {
        "type": "image",
        "url": "/media/KFC/Still 2025-10-22 131141_1.1.1.png"
      },
      {
        "type": "image",
        "url": "/media/KFC/Still 2025-10-22 131226_1.1.1.png"
      },
      {
        "type": "image",
        "url": "/media/KFC/Still 2025-10-22 131359_8.1.1.png"
      },
      {
        "type": "image",
        "url": "/media/KFC/Still 2025-10-22 131442_8.1.2.png"
      },
      {
        "type": "image",
        "url": "/media/KFC/Still 2025-10-22 131533_4.1.1.png"
      }
    ]
  },
  {
    "title": "de Jeugd - een Barkie",
    "tags": [
      "music video",
      "3d",
      "animation",
      "photoscan"
    ],
    "categories": [
      "visual"
    ],
    "date": "2025",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/o2ud4pkwht7lirk6xoxug/jvt-een-barkie_compress.mov?raw=1&rlkey=tklbcpw1d1pqkxkbm5b829x7h&st=1dkta6sc"
      },
      {
        "type": "video",
        "url": "/media/barkie/barkie_480_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/barkie/barkie_480_3_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/barkie/barkie_480_4_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/barkie/barkie_480_thumbnail.mp4"
      }
    ],
    "description": "the classic"
  },
  {
    "title": "Bleedingheart",
    "tags": [
      "bleedingheart"
    ],
    "categories": [
      "visual"
    ],
    "date": "2025-11-06",
    "media": [
      {
        "type": "image",
        "url": "/media/bleedingheart/bh_5k_final.jpg"
      },
      {
        "type": "image",
        "url": "/media/bleedingheart/bh_5k_final_thumbnail.jpg"
      }
    ]
  },
  {
    "title": "Cara <3 Karl",
    "tags": [
      "3d",
      "animation"
    ],
    "categories": [
      "visual",
      "commercial"
    ],
    "date": "2025",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/2hztdy05b8nfm1yic1rvs/GRADED_KL_CARA.mp4?raw=1&rlkey=cdmwv2u614858zlc0wetny647&st=jli4sozt"
      },
      {
        "type": "video",
        "url": "/media/carakarl/cara_karl_thumbnail.mp4"
      },
      {
        "type": "image",
        "url": "/media/carakarl/01._CARAxCARA_crop.jpg"
      },
      {
        "type": "image",
        "url": "/media/carakarl/04.HERO_IMAGE_crop_2.jpg"
      },
      {
        "type": "image",
        "url": "/media/carakarl/1_KL_VOGUERUNWAY_FINAL__STILL_8.webp"
      },
      {
        "type": "image",
        "url": "/media/carakarl/Screenshot 2025-10-23 165012.png"
      },
      {
        "type": "image",
        "url": "/media/carakarl/Screenshot 2025-10-23 165157.png"
      }
    ],
    "description": "Character animation and still rendering for Post Neon"
  },
  {
    "title": "Coco Bryce - Club Tropicana",
    "tags": [
      "music video",
      "3d",
      "animation",
      "vhs"
    ],
    "categories": [
      "visual"
    ],
    "date": "2025",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/oa01lcyfu9hz8vgv7cypo/cococompress_720.mov?raw=1&rlkey=vrt7fg3a1wrfrnjy54dux4l5d"
      },
      {
        "type": "video",
        "url": "/media/cocobryce/cocobryce_480_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/cocobryce/cocobryce_480_3_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/cocobryce/cocobryce_480_thumbnail.mp4"
      }
    ]
  },
  {
    "title": "Danio",
    "tags": [
      "danio"
    ],
    "categories": [
      "commercial"
    ],
    "date": "2025-11-06",
    "media": [
      {
        "type": "image",
        "url": "/media/danio/Screenshot 2025-10-22 115716.png"
      },
      {
        "type": "image",
        "url": "/media/danio/Screenshot 2025-10-22 115747.png"
      },
      {
        "type": "image",
        "url": "/media/danio/Screenshot 2025-10-22 115816.png"
      },
      {
        "type": "image",
        "url": "/media/danio/Screenshot 2025-10-22 115849.png"
      },
      {
        "type": "image",
        "url": "/media/danio/Screenshot 2025-10-22 120105.png"
      },
      {
        "type": "image",
        "url": "/media/danio/Screenshot 2025-10-22 120416.png"
      },
      {
        "type": "image",
        "url": "/media/danio/Screenshot 2025-10-22 120432.png"
      },
      {
        "type": "image",
        "url": "/media/danio/Screenshot 2025-10-22 120454.png"
      }
    ]
  },
  {
    "title": "djb - atlantic",
    "tags": [
      "music video",
      "2d",
      "animation"
    ],
    "categories": [
      "visual",
      "audio"
    ],
    "date": "2025",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/p5ckkezcd1vyisiqxwey6/dowjonesbrotherhood_-_atlantic_compress1080.mov?raw=1&rlkey=w5ohm9p6mzm1qans0lnfg5agr"
      },
      {
        "type": "video",
        "url": "/media/djbalantic/djbatlantic_480_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/djbalantic/djbatlantic_480_3_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/djbalantic/djbatlantic_480_thumbnail.mp4"
      }
    ],
    "description": "Abusing After Effects interpolation algo's"
  },
  {
    "title": "djb - Tazed & Confused",
    "tags": [
      "audio",
      "remix"
    ],
    "categories": [
      "audio"
    ],
    "date": "2025",
    "media": [
      {
        "type": "image",
        "url": "/media/djbtazed/a3674268929_10.jpg"
      },
      {
        "type": "audio",
        "url": "/media/djbtazed/1_side A.m4a"
      },
      {
        "type": "audio",
        "url": "/media/djbtazed/2_side B.m4a"
      }
    ],
    "description": "Syphon Filter (1 and 2) OST remixes",
    "layout": "sidebyside"
  },
  {
    "title": "djb - ~~~",
    "tags": [
      "audio"
    ],
    "categories": [
      "audio"
    ],
    "date": "2025",
    "media": [
      {
        "type": "image",
        "url": "/media/djbuntitled/djbuntitled.png"
      },
      {
        "type": "audio",
        "url": "/media/djbuntitled/01_Lots of Oil.mp3"
      },
      {
        "type": "audio",
        "url": "/media/djbuntitled/02_Atlantic.mp3"
      },
      {
        "type": "audio",
        "url": "/media/djbuntitled/03_NYSE.mp3"
      },
      {
        "type": "audio",
        "url": "/media/djbuntitled/04_40,000k Vanilla.mp3"
      },
      {
        "type": "audio",
        "url": "/media/djbuntitled/05_Multiple Mishaps.mp3"
      },
      {
        "type": "audio",
        "url": "/media/djbuntitled/06_XMTR.mp3"
      },
      {
        "type": "audio",
        "url": "/media/djbuntitled/07_Below Average.mp3"
      },
      {
        "type": "audio",
        "url": "/media/djbuntitled/08_Slow Rise.mp3"
      },
      {
        "type": "audio",
        "url": "/media/djbuntitled/09_Procter & Gamble.mp3"
      },
      {
        "type": "audio",
        "url": "/media/djbuntitled/10_DJX.mp3"
      },
      {
        "type": "audio",
        "url": "/media/djbuntitled/11_Above Average.mp3"
      }
    ],
    "description": "All one take op-1 jams",
    "layout": "sidebyside"
  },
  {
    "title": "djb - dood & verderf",
    "tags": [
      "audio",
      "album"
    ],
    "categories": [
      "visual",
      "audio"
    ],
    "date": "2025",
    "media": [
      {
        "type": "image",
        "url": "/media/doodverderf/djb_dood&verderf_art_final.jpg"
      },
      {
        "type": "audio",
        "url": "/media/doodverderf/mp3/01_I Am Thou.mp3"
      },
      {
        "type": "audio",
        "url": "/media/doodverderf/mp3/02_ondersteboven.mp3"
      },
      {
        "type": "audio",
        "url": "/media/doodverderf/mp3/03_I wish for feathers to sprout from my skin.mp3"
      },
      {
        "type": "audio",
        "url": "/media/doodverderf/mp3/04_sterven = leven.mp3"
      },
      {
        "type": "audio",
        "url": "/media/doodverderf/mp3/05_manoeuvre.mp3"
      },
      {
        "type": "audio",
        "url": "/media/doodverderf/mp3/06_core stability.mp3"
      },
      {
        "type": "audio",
        "url": "/media/doodverderf/mp3/07_stoffelijk overschot.mp3"
      },
      {
        "type": "audio",
        "url": "/media/doodverderf/mp3/08_release your inhibitions, feel the acid rain on your skin.mp3"
      },
      {
        "type": "audio",
        "url": "/media/doodverderf/mp3/09_foraging.mp3"
      },
      {
        "type": "audio",
        "url": "/media/doodverderf/mp3/10_Thou Art I.mp3"
      }
    ],
    "layout": "sidebyside"
  },
  {
    "title": "Duran Lantink - LFW digi show",
    "tags": [
      "2d",
      "animation",
      "compositing"
    ],
    "categories": [
      "visual"
    ],
    "date": "2025",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/y3f2qu6v378vwzzuhmhtk/angel_ho_x_duran_lantink_v1-1080p.mp4?raw=1&rlkey=9u4l9ittgbbd5b61hze8x52j5"
      },
      {
        "type": "video",
        "url": "/media/duran/duran_480_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/duran/duran_480_3_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/duran/duran_480_thumbnail.mp4"
      }
    ],
    "description": "With Daan Couzijn, music by Angel Ho"
  },
  {
    "title": "Eel",
    "tags": [
      "3d",
      "animation",
      "modeling",
      "texturing",
      "unreal"
    ],
    "categories": [
      "visual",
      "audio"
    ],
    "date": "2025-11-06",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/y5nwrx8cu4nrp9xmmydo7/eel-compress.mov?raw=1&rlkey=spstm2sqx43il31a9xt86lj0l"
      },
      {
        "type": "video",
        "url": "/media/eel/eel_480_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/eel/eel_480_3_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/eel/eel_480_thumbnail.mp4"
      }
    ]
  },
  {
    "title": "Estoc ep art",
    "tags": [
      "3d",
      "animation",
      "texturing",
      "rigging"
    ],
    "categories": [
      "visual"
    ],
    "date": "2025",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/wtkaz8bmjoztiu6ki68it/estoc_art_compress.mov?raw=1&rlkey=qxgquepsiez8ijflib95ge93n"
      },
      {
        "type": "video",
        "url": "/media/estoc/estoc_480_thumbnail.mp4"
      },
      {
        "type": "image",
        "url": "/media/estoc/134124795_397270884825962_2381295253738130395_n.jpg"
      }
    ],
    "description": "for Valley Recordings"
  },
  {
    "title": "Fly like a bird",
    "tags": [
      "3d",
      "animation"
    ],
    "categories": [
      "visual"
    ],
    "date": "2025",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/j03u0rkm0tcr4n9yvrxt7/fly_like_a_bird-Original.mp4?raw=1&rlkey=qt9m49ro25jadh15havpwgsy2"
      },
      {
        "type": "video",
        "url": "/media/flylikeabird/fly_like_a_bird_480_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/flylikeabird/fly_like_a_bird_480_thumbnail.mp4"
      }
    ]
  },
  {
    "title": "Halp - Polar",
    "tags": [
      "music video",
      "audio"
    ],
    "categories": [
      "visual"
    ],
    "date": "2025",
    "media": [
      {
        "type": "youtube",
        "url": "https://www.youtube.com/watch?v=LGaYz75mbog"
      },
      {
        "type": "video",
        "url": "/media/halppolar/halppolar_1_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/halppolar/halppolar_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/halppolar/halppolar_3_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/halppolar/halppolar_4_thumbnail.mp4"
      }
    ],
    "description": "360 vid so pump up the quality"
  },
  {
    "title": "Horses and their many issues",
    "tags": [
      "3d",
      "animation"
    ],
    "categories": [
      "visual"
    ],
    "date": "2025",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/zrqet7bil75ekm2321tst/horses_and_their_many_issues_compress.mov?raw=1&rlkey=lrgdqrft8chg76vybd7oduchz"
      },
      {
        "type": "video",
        "url": "/media/horsesissues/horses_1_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/horsesissues/horses_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/horsesissues/horses_3_thumbnail.mp4"
      }
    ]
  },
  {
    "title": "Hang Youth - Steek de Mona Lisa in de fik",
    "tags": [
      "music video",
      "2d",
      "3d",
      "animation",
      "editing"
    ],
    "categories": [
      "visual"
    ],
    "date": "2025",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/7dneo1h7kpt3soltsj17j/HY_MONALISAV1_YOUTUBEUPSCALE-BETER.mp4?raw=1&rlkey=as2wv1joephwvxtd637lx0ugz"
      },
      {
        "type": "video",
        "url": "/media/hymonalisa/hymonalisa_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/hymonalisa/hymonalisa_3_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/hymonalisa/hymonalisa_thumbnail.mp4"
      }
    ]
  },
  {
    "title": "Hang Youth - dat wordt nog wat met Sinterklaas dit jaar",
    "tags": [
      "music video",
      "3d",
      "animation"
    ],
    "categories": [
      "visual"
    ],
    "date": "2025",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/h9cmbctjve15538jpirjo/hysint_compress.mov?raw=1&rlkey=ltfzkvfdj9eftspkmymcqo11m"
      },
      {
        "type": "video",
        "url": "/media/hysint/hysint_1_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/hysint/hysint_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/hysint/hysint_3_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/hysint/hysint_4_thumbnail.mp4"
      }
    ]
  },
  {
    "title": "IJSLAND - IJSLAND",
    "tags": [
      "artwork",
      "3d"
    ],
    "categories": [
      "visual"
    ],
    "date": "2025",
    "media": [
      {
        "type": "image",
        "url": "/media/ijsland/ijslandart.jpg"
      },
      {
        "type": "image",
        "url": "/media/ijsland/ijslandart_thumbnail.jpg"
      }
    ]
  },
  {
    "title": "Lit woke angel",
    "tags": [
      "3d",
      "animation"
    ],
    "categories": [
      "visual",
      "audio"
    ],
    "date": "2025",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/p2t7pi40fayd9ja1ygicl/LITWOKEANIME_FINAL_compress.mov?raw=1&rlkey=ggstu296pe652kxwnmgfosdyu"
      },
      {
        "type": "video",
        "url": "/media/litwokeangel/LITWOKEANIME_1_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/litwokeangel/LITWOKEANIME_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/litwokeangel/LITWOKEANIME_3_thumbnail.mp4"
      }
    ]
  },
  {
    "title": "Monsbot festival",
    "tags": [
      "3d",
      "animation"
    ],
    "categories": [
      "visual"
    ],
    "date": "2025",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/popdtimels7p7w34xeskh/monsbot_animatie_final_h264.mp4?raw=1&rlkey=ttgxz8x0ev1beslgvhzjxhoi3"
      },
      {
        "type": "video",
        "url": "/media/monsbot/monsbot_thumbnail.mp4"
      }
    ]
  },
  {
    "title": "Mtv international ident",
    "tags": [
      "3d",
      "animation",
      "sound design"
    ],
    "categories": [
      "visual",
      "audio"
    ],
    "date": "2025",
    "media": [
      {
        "type": "video",
        "url": "/media/mtv/mtv_international_ident_compress.mov"
      },
      {
        "type": "video",
        "url": "/media/mtv/mtv_1_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/mtv/mtv_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/mtv/mtv_3_thumbnail.mp4"
      }
    ]
  },
  {
    "title": "Notch.fest LA",
    "tags": [
      "3d",
      "dome",
      "animation"
    ],
    "categories": [
      "visual"
    ],
    "date": "2025",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/afc41l0h9f0ijdtpcojt0/notchfest_sphere_compress.mov?raw=1&rlkey=t844xm48q1xqs7e0re1psjidb"
      },
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/w99ej757pfzzf6ql0tn4c/notchfest_unwrap_compress.mov?raw=1&rlkey=a1pjqtlqod912t6h3i6hpju6c"
      },
      {
        "type": "video",
        "url": "/media/notchfest/notchfest_1_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/notchfest/notchfest_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/notchfest/notchfest_3_thumbnail.mp4"
      },
      {
        "type": "image",
        "url": "/media/notchfest/Still 2025-10-21 200355_1.1.1.png"
      },
      {
        "type": "image",
        "url": "/media/notchfest/Still 2025-10-21 200423_1.1.2.png"
      },
      {
        "type": "image",
        "url": "/media/notchfest/Still 2025-10-21 200607_1.1.1.png"
      },
      {
        "type": "image",
        "url": "/media/notchfest/Still 2025-10-21 200657_1.1.2.png"
      },
      {
        "type": "image",
        "url": "/media/notchfest/Still 2025-10-21 200859_1.1.1.png"
      }
    ],
    "description": "visuals for Notch.fest (the minecraft guy). The whole venue was a huge 360 dome."
  },
  {
    "title": "Jonkoklapper - Offer",
    "tags": [
      "music video",
      "3d",
      "animation"
    ],
    "categories": [
      "visual"
    ],
    "date": "2025",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/zxgugomakxgh4obecss9q/jonkoklapperoffer_compress.mov?raw=1&rlkey=grsorrk1r9xvm726r8dgxc1mp"
      },
      {
        "type": "video",
        "url": "/media/offer/offer_1_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/offer/offer_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/offer/offer_3_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/offer/offer_4_thumbnail.mp4"
      }
    ]
  },
  {
    "title": "djb - ondersteboven",
    "tags": [
      "music video",
      "audio",
      "3d",
      "animation"
    ],
    "categories": [
      "visual",
      "audio"
    ],
    "date": "2025",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/jlts3jvdffijdhyu3o5cu/djb_-_ondersteboven_compress.mov?raw=1&rlkey=8kh7ctk01un0d70p3fon6fuvy"
      },
      {
        "type": "video",
        "url": "/media/ondersteboven/onder_1_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/ondersteboven/onder_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/ondersteboven/onder_3_thumbnail.mp4"
      }
    ]
  },
  {
    "title": "Pornhub awards",
    "tags": [
      "3d",
      "animation"
    ],
    "categories": [
      "visual"
    ],
    "date": "2025",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/wcwkx8acew4th2ztrdrj4/15-1080p.mp4?raw=1&rlkey=739uwbwelt0cckqrlqcc7nrcl"
      },
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/xe2ewhjgqkydnu6jyj5ma/12-1080p.mp4?raw=1&rlkey=scb9z4p285bc979xqgxly41ue"
      },
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/fh12m7pteqcf2wbjzbwxe/18-1080p.mp4?raw=1&rlkey=6dmvqxk8sm56reungueov6wkz"
      },
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/dyu98bymfdwzuoylwcz3h/24-720p.mp4?raw=1&rlkey=x4cz3m5t8tus0k8oto9hfhrt7"
      },
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/normepw7q19ecb1ktj7fs/tc-720p.mp4?raw=1&rlkey=cj518dek40wbc4hzhzekn86g8"
      },
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/2qwxmumo6pc96ouv36je6/22-1080p.mp4?raw=1&rlkey=myx5u5ywiqysa6dzpeua8bjyo"
      },
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/2d3eyjdz1xqbb4tdhglvu/13-1080p.mp4?raw=1&rlkey=m0vftnivp0llswcth8ljtq39l"
      },
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/hhy84s1bnqo3rv0v2jr77/09-1080p.mp4?raw=1&rlkey=4fnd9e9jr7hxum59cazlxh9yc"
      },
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/7xl7pbuv4e3pq4ltakcqq/08-1080p.mp4?raw=1&rlkey=yoa6z3ebcei14n2pb3c2ldica"
      },
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/ki0psqakh93ep47ay47ti/04-1080p.mp4?raw=1&rlkey=ffi2r4h2sv9oor6i2atcnxql7"
      },
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/s2u9vgnc7q8cp940hsssw/02-1080p.mp4?raw=1&rlkey=ivmcrxdd1kgm4rsmcwmfsjuto"
      },
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/34l9fdrqgvc37yzeckkm4/01-1080p.mp4?raw=1&rlkey=px2plntblwgve2gwm4p0ggr9h"
      },
      {
        "type": "video",
        "url": "/media/phawards/ph_1_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/phawards/ph_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/phawards/ph_3_thumbnail.mp4"
      }
    ],
    "description": "small selection of stuff we made with Geoffrey Lillemon and Diane Martel (rip) and team."
  },
  {
    "title": "P.L.M.A.I.T.H.",
    "tags": [
      "2d",
      "animation",
      "audio"
    ],
    "categories": [
      "visual",
      "audio"
    ],
    "date": "2025",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/kb1zvh23r71inzvh5cbi7/PLMAITH_001_h264_1080x1080.mov?raw=1&rlkey=bgabhfg9ro9dm4qlqo97c7oni"
      },
      {
        "type": "video",
        "url": "/media/plmaith/plmaith_1_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/plmaith/plmaith_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/plmaith/plmaith_3_thumbnail.mp4"
      },
      {
        "type": "audio",
        "url": "/media/plmaith/mp3/01_Please.mp3"
      },
      {
        "type": "audio",
        "url": "/media/plmaith/mp3/02_Let Me.mp3"
      },
      {
        "type": "audio",
        "url": "/media/plmaith/mp3/03_Assimilate.mp3"
      },
      {
        "type": "audio",
        "url": "/media/plmaith/mp3/04_Into The.mp3"
      },
      {
        "type": "audio",
        "url": "/media/plmaith/mp3/05_Hivemind.mp3"
      }
    ],
    "description": "pls let me assimilate into the hivemind",
    "layout": "sidebyside",
    "allowSimultaneousPlayback": true
  },
  {
    "title": "P.L.M.A.I.T.H. vids",
    "tags": [
      "video",
      "ai",
      "audio"
    ],
    "categories": [
      "visual",
      "audio"
    ],
    "date": "2025",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/n3hp9bkt3jcq7y2mpoo8g/1-please-v2.mp4?raw=1&rlkey=jt2fr5c2yn6cq28n6jz1624bs"
      },
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/yxe1x1eoavkgq7mp2ieh3/2-let-me-v2.mp4?raw=1&rlkey=2577gw728s1q62ie3onm7lnk6"
      },
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/wko7jrvyeu1buf63ikd9u/3-assimilate-v2.mp4?raw=1&rlkey=87xi9z9egszmtkxy2rfv7hvyc"
      },
      {
        "type": "video",
        "url": "/media/plmaithvids/plmaithvids_1_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/plmaithvids/plmaithvids_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/plmaithvids/plmaithvids_3_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/plmaithvids/plmaithvids_4_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/plmaithvids/plmaithvids_5_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/plmaithvids/plmaithvids_6_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/plmaithvids/plmaithvids_7_thumbnail.mp4"
      }
    ],
    "description": "messed up latent self portraits"
  },
  {
    "title": "Poly",
    "tags": [
      "old",
      "2d",
      "animation",
      "film"
    ],
    "categories": [
      "visual",
      "audio"
    ],
    "date": "2025-11-06",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/i00ko4tqewl7h14a7r2pc/poly-1080p.mp4?raw=1&rlkey=g33wl5r0iz93e58zu96amlofd"
      },
      {
        "type": "video",
        "url": "/media/poly/poly_1_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/poly/poly_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/poly/poly_3_thumbnail.mp4"
      }
    ]
  },
  {
    "title": "Praise be",
    "tags": [
      "3d",
      "animation",
      "sound design"
    ],
    "categories": [
      "visual",
      "audio"
    ],
    "date": "2025",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/lifwscq742ac52je5fzoe/_praise_be_compress.mov?raw=1&rlkey=9fder575i1xf5yr9kggi5u461"
      },
      {
        "type": "video",
        "url": "/media/praisebe/praisebe_1_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/praisebe/praisebe_2_thumbnail.mp4"
      }
    ]
  },
  {
    "title": "Slavic Phantasmagoria",
    "tags": [
      "audio",
      "sound design",
      "installation"
    ],
    "categories": [
      "audio"
    ],
    "date": "2025",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/z2dq8rkbc7f4ms3fuxrj6/YTDown.com_YouTube_Cuda-Wianki-Miracles-of-wreaths_Media_tOv5ZJ6N33E_001_1080p.mp4?raw=1&rlkey=xlgocjgxtjpvxxxpv2uq04y32"
      },
      {
        "type": "video",
        "url": "/media/slavic/slavic_1_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/slavic/slavic_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/slavic/slavic_3_thumbnail.mp4"
      },
      {
        "type": "audio",
        "url": "/media/slavic/slavic phantasmagoria ost.mp3"
      }
    ],
    "description": "OST for \"Slavic phantasmagoria. Orphanage of meanings\" by Sonia Górecka with vocals by choir Głośno"
  },
  {
    "title": "Slugabed waterfalls",
    "tags": [
      "music video",
      "film",
      "editing"
    ],
    "categories": [
      "visual"
    ],
    "date": "2025",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/vrdxohm9nmxb7vfpsb5tx/slugabed_-_waterfallssssss_compress.mov?raw=1&rlkey=lzgjzn55t7nguxuyz8a3feje6"
      },
      {
        "type": "video",
        "url": "/media/slugwaterfalls/slugwater_1_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/slugwaterfalls/slugwater_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/slugwaterfalls/slugwater_3_thumbnail.mp4"
      }
    ]
  },
  {
    "title": "Smite",
    "tags": [
      "3d",
      "animation"
    ],
    "categories": [
      "visual"
    ],
    "date": "2025-11-06",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/61dumbjq3ojpyypwm2l48/smite_compress.mov?raw=1&rlkey=aarm3xxha09ez6csn26m4jp4y"
      },
      {
        "type": "video",
        "url": "/media/smite/smite_1_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/smite/smite_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/smite/smite_3_thumbnail.mp4"
      }
    ]
  },
  {
    "title": "Superduper",
    "tags": [
      "3d",
      "animation",
      "vhs",
      "sound design"
    ],
    "categories": [
      "visual",
      "audio"
    ],
    "date": "2025-11-06",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/wulw666msdvninz69qx25/superduper-1080p.mp4?raw=1&rlkey=uuwhd6kyzwisf272ow4jp9lgx"
      },
      {
        "type": "video",
        "url": "/media/superduper/superduper_1_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/superduper/superduper_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/superduper/superduper_3_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/superduper/superduper_4_thumbnail.mp4"
      }
    ]
  },
  {
    "title": "Telegotu",
    "tags": [
      "telegotu"
    ],
    "categories": [
      "commercial",
      "visual"
    ],
    "date": "2025-11-06",
    "media": [
      {
        "type": "image",
        "url": "/media/placeholder-square.jpg"
      }
    ]
  },
  {
    "title": "Titts Woef",
    "tags": [
      "music video",
      "3d",
      "animation"
    ],
    "categories": [
      "visual"
    ],
    "date": "2014",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/0s9qfvrg36xa4hqyevrla/titts_-_woef_compress.mov?raw=1&rlkey=pxzn32i6g0mnggsjiw6rjrtv5"
      },
      {
        "type": "video",
        "url": "/media/tittswoef/woef_1_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/tittswoef/woef_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/tittswoef/woef_3_thumbnail.mp4"
      }
    ]
  },
  {
    "title": "Travis Scott viz",
    "tags": [
      "3d",
      "animation",
      "visuals"
    ],
    "categories": [
      "visual"
    ],
    "date": "2025",
    "media": [
      {
        "type": "image",
        "url": "/media/travisviz/224352512_373555180806826_7687760472423500112_n.jpg"
      },
      {
        "type": "image",
        "url": "/media/travisviz/225272943_373654314117264_4837415256009431978_n.jpg"
      },
      {
        "type": "image",
        "url": "/media/travisviz/307697298_1179705732759743_4406989219120795302_n.jpg"
      },
      {
        "type": "image",
        "url": "/media/travisviz/Screen_Shot_2021-07-26_at_10.48.33_AM_qk808n.webp"
      },
      {
        "type": "image",
        "url": "/media/travisviz/Travis-Scott-Rolling-Loud.webp"
      },
      {
        "type": "image",
        "url": "/media/travisviz/travis_thumbnail.jpg"
      }
    ],
    "description": "with Human Person and a whole team"
  },
  {
    "title": "Yellow Claw mixtape trailer",
    "tags": [
      "3d",
      "animation"
    ],
    "categories": [
      "visual"
    ],
    "date": "2025",
    "media": [
      {
        "type": "video",
        "url": "https://dl.dropboxusercontent.com/scl/fi/4re2wqszew4taw7ma7n1j/yc_mixtapetrailer.mp4?raw=1&rlkey=ad3w66uy38sd0wd0ez3n396jq"
      },
      {
        "type": "video",
        "url": "/media/ycmixtape/ycmix_1_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/ycmixtape/ycmix_2_thumbnail.mp4"
      },
      {
        "type": "video",
        "url": "/media/ycmixtape/ycmix_3_thumbnail.mp4"
      }
    ]
  }
] as Project[];
